name: cvw-rv32imc
# name: cv32e20-rv32imc

# udb_config: cv32e20-rv32imc.yaml
udb_config: cvw-rv32imc.yaml
compiler_exe: "/home/lpt-10x/riscv32/bin/riscv32-unknown-elf-gcc"
ref_model_type: "sail"
ref_model_exe: "/home/lpt-10x/Documents/sail/sail-riscv-Linux-x86_64/bin/sail_riscv_sim"
linker_script: link.ld
dut_include_dir: . # Directory containing DUT specific model_test.h header
