
# This Makefile is auto-generated by riscv-arch-test act framework. Do not edit directly.
.DEFAULT_GOAL := compile
.PHONY: compile

CFLAGS += -O0 -g -mcmodel=medany -nostartfiles -I/home/lpt-10x/Documents/WORK/act4-cvw/riscv-arch-test/work/../tests/env -I/home/lpt-10x/Documents/WORK/act4-cvw/riscv-arch-test/work/../tests/priv/headers
XLEN := 32
ELFS = \

compile: $(ELFS)

:
	mkdir -p $@
